export const data = {
  nodes: [
    {
      id: "Node 1",
      height: 1,
      size: 24,
      color: "rgb(97, 205, 187)",
    },
    {
      id: "Node 2",
      height: 1,
      size: 24,
      color: "rgb(97, 205, 187)",
    },
    {
      id: "Node 3",
      height: 1,
      size: 24,
      color: "rgb(97, 205, 187)",
    },
    {
      id: "Node 4",
      height: 1,
      size: 24,
      color: "rgb(97, 205, 187)",
    },
    {
      id: "Node 5",
      height: 1,
      size: 24,
      color: "rgb(97, 205, 187)",
    },
    {
      id: "Node 6",
      height: 1,
      size: 24,
      color: "rgb(97, 205, 187)",
    },
    {
      id: "Node 7",
      height: 1,
      size: 24,
      color: "rgb(97, 205, 187)",
    },
    {
      id: "Node 8",
      height: 1,
      size: 24,
      color: "rgb(97, 205, 187)",
    },
    {
      id: "Node 9",
      height: 1,
      size: 24,
      color: "rgb(97, 205, 187)",
    },
    {
      id: "Node 0",
      height: 2,
      size: 32,
      color: "rgb(244, 117, 96)",
    },
    {
      id: "Node 1.0",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 1.1",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 1.2",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 1.3",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 2.0",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 2.1",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 2.2",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 2.3",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 2.4",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 2.5",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 2.6",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 3.0",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 3.1",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 3.2",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 3.3",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 3.4",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 3.5",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 4.0",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 4.1",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 4.2",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 4.3",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 4.4",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 4.5",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 4.6",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 5.0",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 5.1",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 5.2",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 6.0",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 6.1",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 6.2",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 6.3",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 6.4",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 6.5",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 6.6",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 6.7",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 6.8",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 7.0",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 7.1",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 7.2",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 7.3",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 7.4",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 7.5",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 7.6",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 7.7",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 7.8",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 8.0",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 8.1",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 8.2",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 8.3",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 8.4",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 9.0",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 9.1",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 9.2",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
    {
      id: "Node 9.3",
      height: 0,
      size: 12,
      color: "rgb(232, 193, 160)",
    },
  ],
  links: [
    {
      source: "Node 0",
      target: "Node 1",
      distance: 80,
    },
    {
      source: "Node 1",
      target: "Node 5",
      distance: 80,
    },
    {
      source: "Node 1",
      target: "Node 1.0",
      distance: 50,
    },
    {
      source: "Node 1",
      target: "Node 1.1",
      distance: 50,
    },
    {
      source: "Node 1",
      target: "Node 1.2",
      distance: 50,
    },
    {
      source: "Node 1",
      target: "Node 1.3",
      distance: 50,
    },
    {
      source: "Node 0",
      target: "Node 2",
      distance: 80,
    },
    {
      source: "Node 2",
      target: "Node 2.0",
      distance: 50,
    },
    {
      source: "Node 2",
      target: "Node 2.1",
      distance: 50,
    },
    {
      source: "Node 2",
      target: "Node 2.2",
      distance: 50,
    },
    {
      source: "Node 2",
      target: "Node 2.3",
      distance: 50,
    },
    {
      source: "Node 2",
      target: "Node 2.4",
      distance: 50,
    },
    {
      source: "Node 2",
      target: "Node 2.5",
      distance: 50,
    },
    {
      source: "Node 2",
      target: "Node 2.6",
      distance: 50,
    },
    {
      source: "Node 0",
      target: "Node 3",
      distance: 80,
    },
    {
      source: "Node 3",
      target: "Node 3.0",
      distance: 50,
    },
    {
      source: "Node 3",
      target: "Node 3.1",
      distance: 50,
    },
    {
      source: "Node 3",
      target: "Node 3.2",
      distance: 50,
    },
    {
      source: "Node 3",
      target: "Node 3.3",
      distance: 50,
    },
    {
      source: "Node 3",
      target: "Node 3.4",
      distance: 50,
    },
    {
      source: "Node 3",
      target: "Node 3.5",
      distance: 50,
    },
    {
      source: "Node 0",
      target: "Node 4",
      distance: 80,
    },
    {
      source: "Node 4",
      target: "Node 4.0",
      distance: 50,
    },
    {
      source: "Node 4",
      target: "Node 4.1",
      distance: 50,
    },
    {
      source: "Node 4",
      target: "Node 4.2",
      distance: 50,
    },
    {
      source: "Node 4",
      target: "Node 4.3",
      distance: 50,
    },
    {
      source: "Node 4",
      target: "Node 4.4",
      distance: 50,
    },
    {
      source: "Node 4",
      target: "Node 4.5",
      distance: 50,
    },
    {
      source: "Node 4",
      target: "Node 4.6",
      distance: 50,
    },
    {
      source: "Node 0",
      target: "Node 5",
      distance: 80,
    },
    {
      source: "Node 5",
      target: "Node 5.0",
      distance: 50,
    },
    {
      source: "Node 5",
      target: "Node 5.1",
      distance: 50,
    },
    {
      source: "Node 5",
      target: "Node 5.2",
      distance: 50,
    },
    {
      source: "Node 0",
      target: "Node 6",
      distance: 80,
    },
    {
      source: "Node 6",
      target: "Node 6.0",
      distance: 50,
    },
    {
      source: "Node 6",
      target: "Node 6.1",
      distance: 50,
    },
    {
      source: "Node 6",
      target: "Node 6.2",
      distance: 50,
    },
    {
      source: "Node 6",
      target: "Node 6.3",
      distance: 50,
    },
    {
      source: "Node 6",
      target: "Node 6.4",
      distance: 50,
    },
    {
      source: "Node 6",
      target: "Node 6.5",
      distance: 50,
    },
    {
      source: "Node 6",
      target: "Node 6.6",
      distance: 50,
    },
    {
      source: "Node 6",
      target: "Node 6.7",
      distance: 50,
    },
    {
      source: "Node 6",
      target: "Node 6.8",
      distance: 50,
    },
    {
      source: "Node 0",
      target: "Node 7",
      distance: 80,
    },
    {
      source: "Node 7",
      target: "Node 7.0",
      distance: 50,
    },
    {
      source: "Node 7",
      target: "Node 7.1",
      distance: 50,
    },
    {
      source: "Node 7",
      target: "Node 7.2",
      distance: 50,
    },
    {
      source: "Node 7",
      target: "Node 7.3",
      distance: 50,
    },
    {
      source: "Node 7",
      target: "Node 7.4",
      distance: 50,
    },
    {
      source: "Node 7",
      target: "Node 7.5",
      distance: 50,
    },
    {
      source: "Node 7",
      target: "Node 7.6",
      distance: 50,
    },
    {
      source: "Node 7",
      target: "Node 7.7",
      distance: 50,
    },
    {
      source: "Node 7",
      target: "Node 7.8",
      distance: 50,
    },
    {
      source: "Node 0",
      target: "Node 8",
      distance: 80,
    },
    {
      source: "Node 8",
      target: "Node 8.0",
      distance: 50,
    },
    {
      source: "Node 8",
      target: "Node 8.1",
      distance: 50,
    },
    {
      source: "Node 8",
      target: "Node 8.2",
      distance: 50,
    },
    {
      source: "Node 8",
      target: "Node 8.3",
      distance: 50,
    },
    {
      source: "Node 8",
      target: "Node 8.4",
      distance: 50,
    },
    {
      source: "Node 0",
      target: "Node 9",
      distance: 80,
    },
    {
      source: "Node 9",
      target: "Node 2",
      distance: 80,
    },
    {
      source: "Node 9",
      target: "Node 9.0",
      distance: 50,
    },
    {
      source: "Node 9",
      target: "Node 9.1",
      distance: 50,
    },
    {
      source: "Node 9",
      target: "Node 9.2",
      distance: 50,
    },
    {
      source: "Node 9",
      target: "Node 9.3",
      distance: 50,
    },
  ],
};

export const data2 = {
  nodes: [
    {
      id: "Sam",
      height: 1,
      size: 24,
      color: "rgb(97, 205, 187)",
      image: "/assets/person.jpg",
    },
    {
      id: "Ebuka",
      height: 2,
      size: 50,
      color: "rgb(244, 117, 96)",
      image: "/assets/ebuka.jpg",
    },
    {
      id: "Chris",
      height: 1,
      size: 24,
      color: "rgb(97, 205, 187)",
    },
    {
      id: "Aaron",
      height: 1,
      size: 24,
      color: "rgb(97, 205, 187)",
    },
    {
      id: "Lydia",
      height: 1,
      size: 24,
      color: "rgb(97, 205, 187)",
    },

    // {
    //   id: "Coding",
    //   height: 0,
    //   size: 12,
    //   color: "rgb(232, 193, 160)",
    // },
    // {
    //   id: "Eating",
    //   height: 0,
    //   size: 12,
    //   color: "rgb(232, 193, 160)",
    // },
    // {
    //   id: "Playing",
    //   height: 0,
    //   size: 12,
    //   color: "rgb(232, 193, 160)",
    // },
    // {
    //   id: "Sleeping",
    //   height: 0,
    //   size: 12,
    //   color: "rgb(232, 193, 160)",
    // },
  ],
  links: [
    {
      source: "Ebuka",
      target: "Sam",
      distance: 80,
    },
    {
      source: "Ebuka",
      target: "Chris",
      distance: 180,
    },
    {
      source: "Ebuka",
      target: "Aaron",
      distance: 100,
    },
    {
      source: "Ebuka",
      target: "Lydia",
      distance: 240,
    },
    {
      source: "Aaron",
      target: "Sam",
      distance: 110,
    },
    {
      source: "Sam",
      target: "Chris",
      distance: 50,
    },
    {
      source: "Chris",
      target: "Aaron",
      distance: 100,
    },
    {
      source: "Sam",
      target: "Lydia",
      distance: 280,
    },
    {
      source: "Lydia",
      target: "Chris",
      distance: 200,
    },
    {
      source: "Lydia",
      target: "Aaron",
      distance: 200,
    },
    // {
    //   source: "Sam",
    //   target: "Sleeping",
    //   distance: 130,
    // },
    // {
    //   source: "Sam",
    //   target: "Eating",
    //   distance: 90,
    // },
    // {
    //   source: "Sam",
    //   target: "Coding",
    //   distance: 80,
    // },
    // {
    //   source: "Chris",
    //   target: "Eating",
    //   distance: 20,
    // },
    // {
    //   source: "Aaron",
    //   target: "Coding",
    //   distance: 90,
    // },
    // {
    //   source: "Ebuka",
    //   target: "Coding",
    //   distance: 100,
    // },
    // {
    //   source: "Sam",
    //   target: "Playing",
    //   distance: 30,
    // },
    // {
    //   source: "Aaron",
    //   target: "Eating",
    //   distance: 120,
    // },
  ],
};
